config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :blog_posts

  # get "/blog_posts/new", to: "blog_posts#new", as: :new_blog_post
  # get "/blog_posts/:id", to: "blog_posts#show", as: :blog_post
  # patch "/blog_posts/:id", to: "blog_posts#update" 
  # delete "blog_posts/:id", to: "blog_posts#destroy"
  # get "/blog_posts/:id/edit", to: "blog_posts#edit", as: :edit_blog_post
  # post "/blog_posts", to: "blog_posts#create", as: :blog_posts

  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  has_rich_text :content

  validates :title, :content, presence: true
  scope :draft, -> { where(published_at: nil) }
  scope :published, -> { where("published_at <= ?", Time.current) }
  scope :scheduled, -> { where("published_at > ?", Time.current) }


  def draft?
    published_at.nil?
  end

  def published?
    published_at? && published_at <= Time.current
  end

  def scheduled?
    published_at? && published_at > Time.current
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

  def index
    @blog_posts = user_signed_in? ? BlogPost.all : BlogPost.published
  end

  def show
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)

    if @blog_post.save
      redirect_to @blog_post, notice: "Creado!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post, notice: "Actualizado"
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @blog_post.destroy    
    redirect_to root_path, notice: "Eliminado!"
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :content, :published_at)
  end

  def set_blog_post
    if user_signed_in?
      @blog_post = BlogPost.find(params[:id])
    else
      @blog_post = BlogPost.published.find(params[:id])
    end
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_form.html.erb
<%= form_for @blog_post do |form| %>
  <% if form.object.errors.any? %>
    <div>
      <% form.object.errors.full_messages.each do |message| %>
        <div>
          <%= message %>
        </div>
      <% end %>
    </div>
    
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
  </div>

  <div>
    <%= form.label :published_at %>
    <%= form.datetime_select :published_at, include_blank: true %>
  </div>
  <%= form.submit %>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Editar</h1>

<%= render "form" %>

app/views/blog_posts/index.html.erb
<h1>Hola</h1>

<%= link_to "Crear nuevo", new_blog_post_path %>

<% @blog_posts.each do |blog_post| %>
  <div>
    <% if blog_post.draft? %>
      <div class="p-2 rounded bg-gray-100 text-gray-900">
        Draft
      </div>
    <% elsif blog_post.scheduled? %>
      <div class="p-2 rounded bg-blue-300 text-gray-900">
        Scheduled
      </div>
    <% end %>
  </div>
  <div>
    <%= blog_post.title %>
    <%= blog_post.content %>
    <div>
      <%= link_to "Ver", blog_post  %>
    </div>
  </div>

<% end %>

app/views/blog_posts/new.html.erb
<h1>Nuevo BlogPost</h1>

<%= render "form" %>

app/views/blog_posts/show.html.erb
<h1>
  <%= @blog_post.title %>
</h1>

<h3>
  <%= @blog_post.content %>
</h3>

<h4>
  <%= link_to "Editar", edit_blog_post_path %>
</h4>

<h4>

  <%= button_to "Eliminar", @blog_post, method: :delete %>
</h4>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="prose mx-auto">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if user_signed_in? %>
      <%= link_to "Profile", edit_user_registration_path %>
      <%= button_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Login", new_user_session_path %>
      <%= link_to "Sign Up", new_user_registration_path %>
    <% end %>
    <%= yield %>
  </body>
</html>